name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test-and-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 15
            - uses: actions/cache@v1
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
            - run: pnpm install
            - run: pnpm test
            - run: pnpm build
